import "./styles/vars.css";
import "./styles/reset.css";
import "./styles/index.css";
import "./styles/fonts.css";
import style from "./layout.module.scss";
import type { Metadata } from "next";
import { Inter, Rubik, Open_Sans } from "next/font/google";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className={style.layout}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
